package fan.testgreen.tgreen.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import fan.testgreen.tgreen.TestS;

import fan.testgreen.tgreen.greendao.TestSDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testSDaoConfig;

    private final TestSDao testSDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testSDaoConfig = daoConfigMap.get(TestSDao.class).clone();
        testSDaoConfig.initIdentityScope(type);

        testSDao = new TestSDao(testSDaoConfig, this);

        registerDao(TestS.class, testSDao);
    }
    
    public void clear() {
        testSDaoConfig.clearIdentityScope();
    }

    public TestSDao getTestSDao() {
        return testSDao;
    }

}
