package fan.testgreen.tgreen.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import fan.testgreen.tgreen.TestS;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "test".
*/
public class TestSDao extends AbstractDao<TestS, Void> {

    public static final String TABLENAME = "test";

    /**
     * Properties of entity TestS.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Ts = new Property(0, String.class, "ts", false, "TS");
    }


    public TestSDao(DaoConfig config) {
        super(config);
    }
    
    public TestSDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"test\" (" + //
                "\"TS\" TEXT);"); // 0: ts
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"test\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestS entity) {
        stmt.clearBindings();
 
        String ts = entity.getTs();
        if (ts != null) {
            stmt.bindString(1, ts);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestS entity) {
        stmt.clearBindings();
 
        String ts = entity.getTs();
        if (ts != null) {
            stmt.bindString(1, ts);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public TestS readEntity(Cursor cursor, int offset) {
        TestS entity = new TestS( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // ts
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestS entity, int offset) {
        entity.setTs(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(TestS entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(TestS entity) {
        return null;
    }

    @Override
    public boolean hasKey(TestS entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
